### ISSUE TITLE
HA docker fails installing python-eq3bt due to failing bluepy installation

### ISSUE THREAD

**Issue by Kugeleis** [linuxserver/docker-homeassistant#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
python-eq3bt installs pulling required dependencies

## Current Behavior
"Unable to install package python-eq3bt==0.1.11" - in the logs

## Steps to Reproduce
1. run latest ha docker stable (as of now 2022.7.6)
2. add [eq3bt integration ](https://www.home-assistant.io/integrations/eq3btsmart/)
3. restart HA - will fail with the error mentioned above

## Environment
**OS: Ubuntu Server 22
**CPU architecture:** x86_64
**How docker service was installed:**
ghcr.io/home-assistant/home-assistant:stable

## Command used to create docker container (run/create/compose/screenshot)
composer file:
```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "[ghcr.io/home-assistant/home-assistant:stable](http://ghcr.io/home-assistant/home-assistant:stable)"
    volumes:
      - /root/docker-home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
```

## Docker logs
[_homeassistant_logs.txt](https://github.com/linuxserver/docker-homeassistant/files/9183316/_homeassistant_logs.txt)
