### ISSUE TITLE
Wrong permissions/ownership on /dev/ttyUSB* for a Zigbee USB Dongle

### ISSUE THREAD

**Issue by xavierdemoor** [linuxserver/docker-homeassistant#56]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
------------------------------

## Expected Behavior
When I plug my USB device, add the correct configuration into my docker-compose.yml (`devices: - "/dev/ttyUSB0:/dev/ttyUSB0"`), I'm able to use this USB device into Home Assistant.

## Current Behavior
The USB is visible into the container but the owner and permissions doesn't allow to use it. The device is owned by root and only root can read/write: `crw------- 1 root root 188, 0 Jul 26 18:42 ttyUSB0`. Home Assistant can't use the USB device.

## Steps to Reproduce

1. Plug a USB device
2. Add the correct configuration to docker-compose.yml
3. Launch the container
4. type `ls -la /dev` to see the permissions for the USB device

## Environment
**OS:** Synology DSM 7
**CPU architecture:** x86_64
**How docker service was installed:** Docker is installed with the Synology package

## Command used to create docker container (run/create/compose/screenshot)
```
  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKER_FOLDER/homeassistant:/config
```

## Log
`Retrying setup: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'`
